SELECT ENAME       --1
FROM EMP
JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC='CHICAGO'

SELECT ENAME,LOC      --2
FROM EMP
JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
ORDER BY LOC

SELECT ENAME FROM EMP E1       --3
WHERE HIREDATE > (SELECT HIREDATE FROM EMP E2 WHERE E1.MGR =E2.EMPNO)


SELECT ENAME,DNAME       --4
FROM EMP
JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO


       SELECT *     --5
FROM EMP
JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO

SELECT ENAME         --6
FROM EMP 
join
JOBHIST
on HIREDATE BETWEEN STARTDATE AND ENDDATE;
