SELECT ENAME   --1
FROM EMP E1 
WHERE E1.EMPNO IN (SELECT MGR FROM EMP E2)

SELECT ENAME,       --2
CASE
	WHEN SAL<= 1000 THEN 1000
	WHEN SAL > 1000 THEN SAL
	END 
AS SAL
FROM EMP

SELECT ENAME,SAL,       --3
CASE
	WHEN SAL<1000 THEN 'LOW'
	WHEN SAL BETWEEN 1000 AND 2500 THEN 'MEDIUM'
	WHEN SAL>2500 THEN 'HIGH' 
	END 
AS RANGE
FROM EMP

SELECT ENAME       ---4
FROM EMP
WHERE JOB='SALESMAN'AND SAL<(SELECT SAL
FROM EMP 
WHERE ENAME='MILLER')

SELECT ENAME      ---5
FROM EMP 
JOIN DEPT  ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC='CHICAGO'

SELECT ENAME        ---6
FROM EMP
WHERE SAL>(SELECT MIN(SAL) 
FROM EMP E1 
WHERE E1.EMPNO IN (SELECT MGR FROM EMP E2))

SELECT EMPNO,ENAME    ---7
FROM EMP
JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO 
WHERE DNAME='ACCOUNTING'


SELECT COUNT(ENAME)      ---8
FROM EMP 
JOIN DEPT  ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC='CHICAGO'

SELECT DISTINCT(JOB)      ---9
FROM EMP 
JOIN DEPT  ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC='CHICAGO'

SELECT DNAME      ----10
FROM DEPT
WHERE DEPTNO  NOT IN (SELECT DEPTNO
FROM EMP)

SELECT ENAME     ---11
FROM EMP 
WHERE MGR IS  NULL

SELECT ENAME,JOB  --12
FROM EMP      
JOIN DEPT  ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC='NEWYORK' AND COMM>1000

SELCET ENAME,
CASE
	WHEN SAL>1000 THEN SAL
	WHEN SAL<=1000 THEN 1000
END AS SAL
FROM EMP
